### ISSUE TITLE
Missing Express types

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#10]
Hi,
I'm hitting a transpile error when using the routing npm package without the other fhir-works components:
```
node_modules/fhir-works-on-aws-routing/lib/app.d.ts:2:119 - error TS2307: Cannot find module 'express-serve-static-core' or its corresponding type declarations.

2 export declare function generateServerlessRouter(fhirConfig: FhirConfig, supportedGenericResources: string[]): import("express-serve-static-core").Express; 
```
Just need to add `@types/express-serve-static-core` into the dependencies.
Thanks!
Allan

**Comment by SanketD92** [comment]
Thanks for providing the solution to this issue, @AllanHodkinson. We will make the required changes soon.
