### ISSUE TITLE
Support for operations

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#12]
Hi AWS team,
As far as I can see the router doesn't yet handle type or systems operations yet (https://www.hl7.org/fhir/operations.html).  Is this something on the roadmap or is it out of the scope of this development?

Many thanks,
Allan

**Comment by rsmayda** [comment]
Hey Allan! 

This router component supports most of the type/system operations. To enable the operations a configuration is passed in from the deployment package found [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L58). 

If you have further questions let us know 👍 
Robert

**Comment by AllanHodkinson** [comment]
Hi Robert,
Thanks for coming back to me.
I can see that we can configure the router to use different interactions, but these are bound to the types TypeOperation/SystemOperation (https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/constants.ts).
What I'm looking to do is to implement an RPC like operation on a resource type e.g. `POST Patient/$initialise` as per the FHIR spec in the link above.   Looking through the Express stack I can't see anything that would handle it though, hence my question about roadmap & project scope etc.
Thanks,
Allan

**Comment by rsmayda** [comment]
Thanks for the clarification! This is the first request I know of talking about this sort of functionality. As of right now it is not prioritized. If this is something you require soon we would be happy to talk more in detail or perhaps talk about co-development efforts!

**Comment by AllanHodkinson** [comment]
No problem, this is definitely out of the scope of a basic FHIR server implementation, but it is a useful feature hence the question re the roadmap.  Should we arrange a call if this is something you'd think about doing?

**Comment by rsmayda** [comment]
For next steps lets plan on bringing this up on a future call to make sure we understand the use-cases. For now I will be closing this, but feel free to open if you need immediate response.
