### ISSUE TITLE
GET returns 404 unless id param matches the case of the stored resource

### ISSUE THREAD

**Issue by chrisbednarski** [awslabs/fhir-works-on-aws-routing#130]
FHIR resource ids are stored in a case sensitive way in dynamodb
When a resource is created via the POST operation with a lower case id, I am not able to retrieve it (via  the GET) with an upper or mixed case id

**To Reproduce**
1. POST to fhir/MedicationReqest using a lower case id
2. GET fhir/MedicationReqest/upper case of the same id
3. See Not Found error 404

**Expected behavior**
Resource is found and returned with status code 200

**Versions (please complete the following information):**
 - Release Version 6.1.1

**Comment by rsmayda** [comment]
Hey @chrisbednarski! I am struggling to find FHIR documentation that says IDs are case-insensitive. Could you provide any documentation you have, or perhaps explain your use-case?

**Comment by chrisbednarski** [comment]
I haven't seen this mentioned in the spec either.

We've discovered this during our dev/validation process and the thinking is that since the IDs are guids, they're not case sensitive.

so, c9d47c75-e414-49f1-9561-e70efaa645ce is the same as C9D47C75-E414-49F1-9561-E70EFAA64BCE

Theoretically, with multiple 3rd parties connecting to an endpoint, if one uses lower case ids, another one uses upper case ids, we will end up with unexpected 404s

**Comment by rsmayda** [comment]
Yeah looking at [RFC4122](https://datatracker.ietf.org/doc/html/rfc4122#section-3) spec on UUIDs
> The hexadecimal values "a" through "f" are output as lower case characters and are **case insensitive on input**

The RFC aside, I would hope clients should assume fhir ids are case-sensitive. That said, if you have clients mixing up the IDs please let us know

**Comment by chrisbednarski** [comment]
We can work around this by specifying the requirement of lower case ids in our documentation. Thanks
