### ISSUE TITLE
[Bug] When using $docref and having multiple documents in period it does not return the latest

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-routing#132]
**Describe the bug**
When using $docref with DocumentReference and having multiple documents with in the same period it does not return the latest, it will return the first with in that period.
Example Call: DocumentReference/$docref?patient=Patient/8aae785b-4228-45aa-b543-10dc79707ded

**Expected behavior**
It should return the latest document within that period for the DocumentReference.

**Additional context**
Document1 entered on 2021-09-16 for the period with a start of 2021-09-15.
Document2 entered on 2021-09-17 for the period with a start of 2021-09-15. 

It will currently return Document1.

Currently the sort for the latest looks like
searchParams = { _sort: '-period', _count: '1', ...searchParams };

**Comment by ssvegaraju** [comment]
Hi, looks like Nestor merged in the changes to also sort by date within periods [here.](https://github.com/awslabs/fhir-works-on-aws-routing/pull/131)! I'm going to close this issue for now, but feel free to reopen if this didn't resolve the issue.
