### ISSUE TITLE
[Feature Request] Log cloudfront request headers for downstream (Goelocation) analytics 

### ISSUE THREAD

**Issue by medhost-jshaver** [awslabs/fhir-works-on-aws-routing#136]
**Is your feature request related to a problem? Please describe.**

We have a need to perform downstream analytics on the requests made to fhirworks and as part of this analytics we need data around geolocation. API Gateway appears to have cloudfront headers available as part of the request and these cloudfront headers contain all the data we require.

Cloudfront request headers that we are interested in:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-cloudfront-headers.html

**Describe the solution you'd like**
- Log request headers as part of routing package
- Selectively log header values that are not sensitive in nature
- Perhaps make this conditional logging based on an environment variable?

**Describe alternatives you've considered**
- Using API gateway execution logs, but the 1024 byte limit truncated the request information
This also logs the sensitive header attributes like JWT token
- Using API gateway access logs, but these only appear to have access to the "context" object associated with the request coming to API gateway. The cloudfront headers do not appear to be accessible from this context object. See here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-logging-variables.html

**Comment by nguyen102** [comment]
Thank you for creating this feature request, we've added this to our team's backlog.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
