### ISSUE TITLE
[Feature Request] MIME type application/fhir+json

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#146]
Hi Robert & team,
One of our team members had a query today about the MIME type returned by the routing module, in that it is `application/json` rather than `application/fhir+json` as the specification suggests _should_ be used (https://www.hl7.org/fhir/http.html#mime-type).

This is clearly not a show stopper as it's never been raised as an issue on here, or by any of our customers, but I'm wondering if you'd had any thoughts about this?

Many thanks,
Allan

**Comment by Bingjiling** [comment]
Hi @AllanHodkinson , 

Thanks for reaching out! We'll look into updating the MIME type. 

Thanks,
Yanyu

**Comment by AllanHodkinson** [comment]
Thanks Yanyu, there is some guidance on response behaviour for different scenarios on that web page I've linked above.

**Comment by Bingjiling** [comment]
Hi Allan,

This issue has been fixed and released in [v6.3.1](https://github.com/awslabs/fhir-works-on-aws-routing/releases/tag/v6.3.1).   Thanks for you help identifying this issue! 

Cheers,
Yanyu
