### ISSUE TITLE
Support for CORS headers

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#15]
Hi AWS team,
For server integration with web services we need to supply CORS headers & support pre-flight requests. The HL7 spec says that FHIR servers SHOULD implement this see https://www.hl7.org/fhir/security.html#http

I've added a PR which adds this to the router (we've deployed this and tested with Postman & several web apps so we know it works!).  

This is a basic implementation - the extension would be to add a cors config (e.g `CorsOptions`) into the server section in FhirConfig (https://github.com/awslabs/fhir-works-on-aws-interface) to allow middleware configuration if required.

For deployment purposes we also need to add an unauthorized OPTIONS route to the API gateway which routes to the deployment Lambda. So this is an update to the serverless template within https://github.com/awslabs/fhir-works-on-aws-deployment.  We're not using the serverless framework so not sure how to do this.

Regards,
Allan

**Comment by rsmayda** [comment]
Really great - proactive work! Let us review the spec and determine if we want to proceed with this approach for now (turning on CORS) or if we want to pass it through the interface as suggested.
