### ISSUE TITLE
change content-type to accept header

### ISSUE THREAD

**Issue by liquid36** [awslabs/fhir-works-on-aws-routing#167]
Hi!
I think that is better to check for de **Accept** header rather than the **ContentType** header.  Accept header is about what the client expect. 

https://github.com/awslabs/fhir-works-on-aws-routing/blob/cb044c37620248a0bd5f261761dd9dc09dbfa426/src/router/middlewares/setContentType.ts#L16

Particulary, i'm going throw ONC Certification, and the **$export test** expect to have an _application/json_ response, not a _application/fhir+josn_ response. 

What do you think?

**Comment by Bingjiling** [comment]
Hi @liquid36,

Thanks for spotting the issue! I've checked the FHIR spec and you're right about this one. As this is a one-line change, do you want to take the opportunity and create a PR for it? 

Thanks,
Yanyu

**Comment by liquid36** [comment]
Yes, no problem. 

#168
