### ISSUE TITLE
[Feature Request] Support resolving temporary bundle references in URI fields

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-routing#174]
#**Is your feature request related to a problem? Please describe.**
I would like to create FHIR resources via Bundle. There are two entries in the Bundle, and one entry references to another by `uri` type field. The problem is the `uri` type referencing is not supported. 

**Describe the solution you'd like**
Support `uri` and `url` type field reference. Here is[ the PR link](https://github.com/awslabs/fhir-works-on-aws-routing/pull/175).

**Describe alternatives you've considered**
N/A

**Additional context**
This is a sample Bundle that contains `uri` type field - `action.definitionUri`.
```
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
        "resource": {
            "id": "1,
            "resourceType" : "PlanDefinition",
            "name" : "plan definition 1",
            "status" : "active",
            },
            "fullUrl": "https://us-west-2.amazonaws.com/dev/PlanDefinition/1",
            "request": {
                "method": "POST",
                "url": "PlanDefinition"
            }
        },
        {
            "resource": {
                "resourceType": "PlanDefinition",
                "name": "plan definition 2",
                "status": "active",
                "action": [
                    {
                        "definitionUri": "PlanDefinition/1"
                    }
                ],
                "id": "2"
            },
            "request": {
                "method": "POST",
                "url": "PlanDefinition"
            },
            "fullUrl": "https://us-west-2.amazonaws.com/dev/PlanDefinition/2"
        }
    ]
}
```

**Comment by kcadette** [comment]
Hello @lquanx
Thank you for your request and PR! We will review it

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
