### ISSUE TITLE
[Feature Request] Support multi tenant Authorization services

### ISSUE THREAD

**Issue by liquid36** [awslabs/fhir-works-on-aws-routing#176]
Do you have any approach in having custom authorization services per tenant? I have some tenant which have special authorization method and others have SMART Authorization.  

Do you think is it possible?

**Comment by ssvegaraju** [comment]
Hi, we don't currently support different authorization servers per tenant. However, this is an interesting use case, and I'll take it back to the team to see if it's possible and get it on our backlog! Thanks for bringing this up.

**Comment by ssvegaraju** [comment]
Hey @liquid36,
I took this back to the team, and we appreciate the feature request, but this isn't something we are considering adding at this time. If more feedback comes in on this feature, it may be something we could consider at that point, but there are currently no plans.

Thanks,
Sukeerth
