### ISSUE TITLE
[Feature Request] Use the URLPattern API instead of Regular Expressions for Subscriptoin Endpoint Whitelisting

### ISSUE THREAD

**Issue by jmrah** [awslabs/fhir-works-on-aws-routing#179]
Please see [issue #739 in the deployment module](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/739) for the issue description, if that isn't a problem.  This is just the routing module counterpart to that linked issue.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
