### ISSUE TITLE
Bundle filtering for global operations

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#33]
Hi AWS team,
In the current router implementation, the `search-system` & `history-system` operations don't make a call to `this.authService.authorizeAndFilterReadResponse` after the response Bundle has been formed.  Is this by design or is it an omission?

Many thanks,
Allan

**Comment by rsmayda** [comment]
Excellent callout Allan! By omission mainly due to us not supporting `search`/`history` `-system`.

This will be a relatively small change we will get it prioritized quickly

FYI make change here: https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/routes/rootRoute.ts
