### ISSUE TITLE
Create interaction without response causes runtime error

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-routing#53]
The return type of the persistence component `create` method is of type `GenericResponse`.  The `response` element is optional, if it's not present we get an undefined runtime error from this line of code:

https://github.com/awslabs/fhir-works-on-aws-routing/blob/8134be9422fce238c205532a78f915c26dc40834/src/router/routes/genericResourceRoute.ts#L175

Solution is to test for existence of `response` before testing for for existence of `response.meta`.
I _think_ that the Express response .send should work as expected if response is undefined.

**Comment by nguyen102** [comment]
Thank you for bringing this up and the PR to fix it. Closing this GH Issue as this is now resolved.
