### ISSUE TITLE
Incorrect REST Security ValueSet in CapabilityStatement

### ISSUE THREAD

**Issue by emilhdiaz** [awslabs/fhir-works-on-aws-routing#60]
According to Aegis Touchstone, the ValueSet in use in the CapabilityStatement to describe the system's rest security capabilities is incorrect. The ValueSet used in `rest.security.service[].coding[].system` should be `http://hl7.org/fhir/ValueSet/restful-security-service`.

![Screen Shot 2021-02-22 at 12 18 35 AM](https://user-images.githubusercontent.com/2886234/108665939-145c8b80-74a4-11eb-8328-2bbce1b7f462.png)

**Comment by rsmayda** [comment]
Ahh good eye look like our response is: "https://www.hl7.org/fhir/codesystem-restful-security-service.html"
